"""
Communication Agent Module
Handles sending summaries and todo lists via email and other channels
"""

from typing import Dict
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import base64
from datetime import datetime

# ============================================================================
# Email Sender Agent
# ============================================================================

def email_sender_agent(state: Dict) -> Dict:
    """Sends prioritized todo list via email"""
    print("📨 Email Sender: Preparing to send todo list...")
    
    prioritized_tasks = state['prioritized_tasks']
    
    if not prioritized_tasks:
        print("ℹ️  No tasks to send - skipping email")
        state['email_sent'] = False
        state['email_status'] = "No tasks to send"
        return state
    
    try:
        # Reuse Gmail service from state (already authenticated by email_collector_agent)
        service = state.get('gmail_service')
        
        if not service:
            error_msg = "Gmail service not available. Email collector may have failed."
            state['errors'].append(error_msg)
            state['email_sent'] = False
            state['email_status'] = error_msg
            print(f"✗ {error_msg}")
            return state
        
        # Get user's email address
        profile = service.users().getProfile(userId='me').execute()
        user_email = profile['emailAddress']
        
        # Format email content
        email_body = format_todo_email(prioritized_tasks, state['time_range_hours'])
        
        # Create email message
        message = MIMEMultipart('alternative')
        message['To'] = user_email
        message['From'] = user_email
        message['Subject'] = f"🎯 Your Prioritized Todo List - {datetime.now().strftime('%b %d, %Y')}"
        
        # Add both plain text and HTML versions
        text_part = MIMEText(email_body['text'], 'plain')
        html_part = MIMEText(email_body['html'], 'html')
        
        message.attach(text_part)
        message.attach(html_part)
        
        # Encode and send
        raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode('utf-8')
        send_message = {'raw': raw_message}
        
        result = service.users().messages().send(userId='me', body=send_message).execute()
        
        state['email_sent'] = True
        state['email_status'] = f"Successfully sent to {user_email}"
        state['email_message_id'] = result['id']
        
        print(f"✓ Todo list sent to {user_email}")
        
    except Exception as e:
        error_msg = f"Email sending error: {str(e)}"
        state['errors'].append(error_msg)
        state['email_sent'] = False
        state['email_status'] = error_msg
        print(f"✗ {error_msg}")
    
    return state

# ============================================================================
# Email Formatting Helper
# ============================================================================

def format_todo_email(tasks, time_range_hours):
    """Formats todo list for email (both plain text and HTML)"""
    
    # Group by priority
    priority_groups = {'P0': [], 'P1': [], 'P2': [], 'P3': []}
    for task in tasks:
        priority = task.get('priority', 'P3')
        priority_groups[priority].append(task)
    
    # Plain text version
    text_lines = []
    text_lines.append(f"Your Prioritized Todo List")
    text_lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    text_lines.append(f"Time Range: Last {time_range_hours} hours")
    text_lines.append(f"Total Tasks: {len(tasks)}")
    text_lines.append("")
    text_lines.append("="*70)
    text_lines.append("")
    
    priority_labels = {
        'P0': 'CRITICAL',
        'P1': 'HIGH',
        'P2': 'MEDIUM',
        'P3': 'LOW'
    }
    
    for priority in ['P0', 'P1', 'P2', 'P3']:
        priority_tasks = priority_groups[priority]
        if priority_tasks:
            text_lines.append(f"{priority_labels[priority]} ({len(priority_tasks)} tasks)")
            text_lines.append("-" * 70)
            
            for i, task in enumerate(priority_tasks, 1):
                text_lines.append(f"\n{i}. {task['task']}")
                text_lines.append(f"   Requested by: {task['requested_by']} ({task['source']})")
                text_lines.append(f"   Action: {task.get('recommended_action', 'Review')}")
                text_lines.append(f"   Effort: {task.get('estimated_effort', 'Unknown')}")
                text_lines.append(f"   Why: {task.get('priority_reason', 'N/A')}")
            
            text_lines.append("")
    
    text_lines.append("="*70)
    text_lines.append("")
    text_lines.append("This email was automatically generated by your Multi-Agent Summarizer.")
    
    # HTML version
    html_lines = []
    html_lines.append("""
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .header { background-color: #4A90E2; color: white; padding: 20px; border-radius: 5px; }
            .task-section { margin: 20px 0; }
            .priority-header { 
                padding: 10px; 
                border-radius: 5px; 
                margin: 15px 0 10px 0;
                font-weight: bold;
            }
            .p0 { background-color: #ff4444; color: white; }
            .p1 { background-color: #ff9944; color: white; }
            .p2 { background-color: #ffdd44; color: #333; }
            .p3 { background-color: #44dd44; color: white; }
            .task-card { 
                border-left: 4px solid #4A90E2; 
                padding: 15px; 
                margin: 10px 0; 
                background-color: #f9f9f9;
                border-radius: 3px;
            }
            .task-title { font-size: 16px; font-weight: bold; margin-bottom: 10px; }
            .task-meta { font-size: 14px; color: #666; margin: 5px 0; }
            .task-action { background-color: #e8f4f8; padding: 8px; border-radius: 3px; margin: 5px 0; }
            .footer { margin-top: 30px; padding: 15px; background-color: #f0f0f0; border-radius: 5px; font-size: 12px; color: #666; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🎯 Your Prioritized Todo List</h1>
            <p>Generated: """ + datetime.now().strftime('%B %d, %Y at %I:%M %p') + """</p>
            <p>Time Range: Last """ + str(time_range_hours) + """ hours | Total Tasks: """ + str(len(tasks)) + """</p>
        </div>
    """)
    
    priority_emojis = {
        'P0': '🔴',
        'P1': '🟠',
        'P2': '🟡',
        'P3': '🟢'
    }
    
    priority_classes = {
        'P0': 'p0',
        'P1': 'p1',
        'P2': 'p2',
        'P3': 'p3'
    }
    
    for priority in ['P0', 'P1', 'P2', 'P3']:
        priority_tasks = priority_groups[priority]
        if priority_tasks:
            html_lines.append(f"""
            <div class="task-section">
                <div class="priority-header {priority_classes[priority]}">
                    {priority_emojis[priority]} {priority_labels[priority]} ({len(priority_tasks)} tasks)
                </div>
            """)
            
            for task in priority_tasks:
                html_lines.append(f"""
                <div class="task-card">
                    <div class="task-title">{task['task']}</div>
                    <div class="task-meta">👤 Requested by: <strong>{task['requested_by']}</strong> ({task['source']})</div>
                    <div class="task-action">📝 <strong>Action:</strong> {task.get('recommended_action', 'Review')}</div>
                    <div class="task-meta">⏱️ Effort: {task.get('estimated_effort', 'Unknown')}</div>
                    <div class="task-meta">💡 Why: {task.get('priority_reason', 'N/A')}</div>
                </div>
                """)
            
            html_lines.append("</div>")
    
    html_lines.append("""
        <div class="footer">
            <p>This email was automatically generated by your Multi-Agent Communication Summarizer.</p>
            <p>Reply to this email will go to your own inbox.</p>
        </div>
    </body>
    </html>
    """)
    
    return {
        'text': '\n'.join(text_lines),
        'html': ''.join(html_lines)
    }

